#!/usr/bin/env bash
set -e

SRC=$(pwd)/blobs
SHELL=/bin/bash
AWK=awk

read_spec() {
  local spec="$1"
  $AWK '/^files:/ {
    while (getline) {
      if ($1 == "-") {
        if ($3 ~ /#/) {
          url=$3$4;
          sub(/#/, "", url)
          print $2"@"url;
        }
      } else {
        next;
      }
    }
  }' "$spec"
}

exec_download() {
  local output="$1"
  local url="$2"
  local package=$(dirname "${output}")
  local src=$(basename "${output}")
  (
    cd ${SRC}
    if [ ! -s "${output}" ]; then
      echo "  Downloading ${url} ..."
      mkdir -p "${package}"
      curl -L --fail "${url}" -o "${output}"
    fi
  )
}

add_blob() {
  local blob="$1"
  bosh add-blob ${SRC}/${1} ${1} || true
}

remove_stale() {
  local spec_files=""
  for spec in $(read_spec "${script}"); do
    local downloadfile=$(echo $spec | cut -d'@' -f 1)
    local filename=$(echo $downloadfile | cut -d'/' -f 2)
    spec_files="$filename $spec_files"
  done
  # Remove any files in blobs/sysdig-agent that aren't in spec
  for saved_file in $(ls blobs/sysdig-agent); do
    if [[ !("$spec_files" =~ .*"$saved_file".*) ]]; then
      bosh remove-blob "sysdig-agent/$saved_file"
    fi
  done
}

update_verison() {
  old_version=$(cat $(pwd)/version)

  sed -i 's|SYSDIG_AGENT_VERSION=.*|SYSDIG_AGENT_VERSION="'$1'"|' ./packages/sysdig-agent/packaging
  sed -i 's|'$old_version'|'$1'|g' ./packages/sysdig-agent/spec
}

main() {
  # When using local blobs, its useful to start with an empty slate
  if [ $CLEAN_BLOBS ]; then
    > config/blobs.yml
  fi

  update_verison $1

  for script in $(pwd)/packages/*/spec ; do
    local base=$(dirname "${script}")
      echo "* Procesing ${script} ..."

      for spec in $(read_spec "${script}"); do
        local downloadfile=$(echo $spec | cut -d'@' -f 1)
        local file_version=$(echo $downloadfile | grep -o -h -e "[0-9]\.[0-9]\.[0-9][~]*[r]*[c]*\.*[0-9]*")
        local downloadurl=$(echo $spec | cut -d'@' -f 2)

        exec_download "${downloadfile}" "${downloadurl}"
        add_blob "${downloadfile}"
      done
  done

  remove_stale
}

# Run!
mkdir -p $SRC
main $@